### PR TITLE
4.1

### PR DESCRIPTION
**Pull request by minrk**

### CODE REVIEW

**Comment by takluyver** [comment]
Windows builds failed, but I don't understand why.

```
TEST START: nbformat-4.1.0-py35_0
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    decorator-4.0.10           |           py35_0          12 KB  conda-forge
    ipython_genutils-0.1.0     |           py35_0          33 KB  defaults
    jsonschema-2.5.1           |           py35_0         108 KB  conda-forge
    traitlets-4.2.2            |           py35_0         116 KB  conda-forge
    jupyter_core-4.1.0         |           py35_0         104 KB  conda-forge
    nbformat-4.1.0             |           py35_0         359 KB  local
    ------------------------------------------------------------
                                           Total:         732 KB
The following NEW packages will be INSTALLED:
    certifi:          2016.8.2-py35_0 conda-forge
    decorator:        4.0.10-py35_0   conda-forge
    ipython_genutils: 0.1.0-py35_0    defaults   
    jsonschema:       2.5.1-py35_0    conda-forge
    jupyter_core:     4.1.0-py35_0    conda-forge
    nbformat:         4.1.0-py35_0    local      
    pip:              8.1.2-py35_0    conda-forge
    python:           3.5.2-2         conda-forge
    setuptools:       25.1.6-py35_0   conda-forge
    traitlets:        4.2.2-py35_0    conda-forge
    vs2015_runtime:   14.0.25420-0    conda-forge
    wheel:            0.29.0-py35_0   conda-forge
    wincertstore:     0.2-py35_0      conda-forge
C:\conda\conda-bld\test-tmp_dir>call activate.bat C:\conda\envs\_test 
===== testing package: nbformat-4.1.0-py35_0 =====
import: 'nbformat'
===== nbformat-4.1.0-py35_0 OK =====
TESTS FAILED: nbformat-4.1.0-py35_0
Command exited with code 1
```

**Comment by ocefpaf** [comment]
> Windows builds failed, but I don't understand why.

Explanation: https://github.com/conda-forge/jupyter_core-feedstock/pull/5#issuecomment-239227945

Temporary workaround: https://github.com/minrk/nbformat-feedstock/pull/1

**Comment by minrk** [comment]
Since conda-build 1.21.11 is producing packages that cannot be installed by any released version of conda, I would rather pin conda-build than remove the call to pip while this gets worked out. What's the best way to do that (@msarahan?)

**Comment by msarahan** [comment]
Sorry, but I don't think that reverting conda build will work. It's not that conda build changed how pip behaves, but rather just that it now properly detects binary prefixes embedded in the entry point executables. Because pip is embedding these prefixes into the executables, you instead need to figure out when pip started doing that, and pin pip. I am pretty sure that older versions of conda build will still have broken entry points, and moreover they simply won't be fixable by any version of conda. 

I have also thought about using pip on Mac and Linux, but the old way on Windows to avoid these embedded prefix exes, until the conda support for them is more generally available. I am not sure if that is palatable to you.

**Pull request merged**
