### PR TITLE
switch to noarch: python

### PR DESCRIPTION
**Pull request by djsutherland**
Switch [to `noarch: python`](https://github.com/conda-forge/conda-forge.github.io/blob/master/src/meta.rst#building-noarch-packages). As an important side-effect, cause an actual release of 4.4.0 since the previous build was broken by the tokens issue.

### CODE REVIEW

**Comment by djsutherland** [comment]
Ugh, I'm an idiot. Trying that again....

**Review by jakirkham — APPROVED** [review]

**Comment by djsutherland** [comment]
Failed due to a seeming conda-build bug: https://github.com/conda/conda-build/issues/2362.

Will send a PR with an empty change to make a build in the meantime.

**Comment by jakirkham** [comment]
Toggling for CIs.

**Comment by jakirkham** [comment]
Could you please rebase this @dougalsutherland? I think that should cleanup the conflict (just complaining about the different re-renderings). Then expect this will pass.

**Comment by djsutherland** [comment]
Rebased, but it still makes an invalid `jupyter-trust` entry point for me locally: https://github.com/conda/conda-build/issues/2362 seems like an actual bug.

**Comment by jakirkham** [comment]
Thanks. Alright let's see how that issue plays out.

**Comment by djsutherland** [comment]
Fixed by #12.

**Pull request closed without merging**
